version: "3.9"

services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: enterate-postgres
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build: .
    container_name: enterateapi-rest
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8001:8001"
    volumes:
      - ./app:/app       # Monta la carpeta de la API
      - ./etl:/app/etl   # Monta la carpeta de ETL
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload

volumes:
  pg_data:
